#!/bin/bash
file="result"
[[ -f "$file" ]] && rm -f "$file"
file="traktacc"
[[ -f "$file" ]] && rm -f "$file"
flexget trakt show >> ~/traktacc
traktaccount=$(grep -w -R 'account' /var/lib/deluge/.flexget/secretfile.yml | cut -c 12-)
search=$( grep -m 1 $traktaccount traktacc | cut --characters=1-${#traktaccount} ) #cut  to only see charcter 1- how ever long traktacc$
    if [[ $search == $traktaccount ]] ; then
        echo "Verifing user authorization"
    else
      while [[ $search != $traktaccount  ]] ;
      do
        echo "Please input you pin for user $traktaccount"
        read input </dev/tty
        flexget trakt auth $traktaccount $input >> ~/result
        flexget trakt show >> ~/traktacc
        traktaccount=$(grep -w -R 'account' /var/lib/deluge/.flexget/secretfile.yml | cut -c 12-)
        search=$( grep -m 1 $traktaccount traktacc | cut --characters=1-${#traktaccount} ) #cut  to only see charcter 1- how ever long traktacc$
      done
    fi

file="result"
[[ -f "$file" ]] && rm -f "$file"
file="traktacc"
[[ -f "$file" ]] && rm -f "$file"
echo "Trakt Account $traktaccount is autorized"
exit

